# Generated by Django 5.2.17 on 2026-08-20 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('collection', '0002_questionnaire_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSurveyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_open', models.BooleanField(default=False, help_text='Open links let the respondent pick the county. County links are locked to one county.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('county', models.ForeignKey(blank=True, help_text='If set, every response is stored against this county. If blank, the person chooses a county.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_survey_links', to='catalog.county')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('survey_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_survey_links', to='catalog.surveyperiod')),
            ],
            options={
                'ordering': ['county__name'],
            },
        ),
        migrations.CreateModel(
            name='IndividualResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=160)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(blank=True, choices=[('permanent', 'Permanent & pensionable'), ('contract', 'Contract'), ('casual', 'Temporary / casual'), ('other', 'Other')], max_length=20)),
                ('years_in_role', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('current_basic', models.DecimalField(decimal_places=2, max_digits=14)),
                ('house_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('commuter_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('airtime', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('other_allowances', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=160)),
                ('respondent_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_responses', to='catalog.county')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_responses', to='catalog.benchmarkjob')),
                ('survey_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_responses', to='catalog.surveyperiod')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='collection.staffsurveylink')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffsurveylink',
            constraint=models.UniqueConstraint(condition=models.Q(('county__isnull', False), ('is_open', False)), fields=('survey_period', 'county'), name='unique_county_staff_link'),
        ),
        migrations.AddConstraint(
            model_name='staffsurveylink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('survey_period',), name='unique_open_staff_link'),
        ),
    ]
