# Generated by Django 5.2.17 on 2026-08-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_job_groups_and_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpayrow',
            name='median_basic',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy field. Analysis uses the midpoint of min and max; this is only a fallback if both are blank.', max_digits=14, null=True),
        ),
    ]
