# Generated by Django 5.2.17 on 2026-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('collection_admin', 'Collection administrator'), ('consultant', 'Field consultant'), ('county', 'County respondent'), ('analyst', 'Analyst')], default='county', max_length=20),
        ),
    ]
